### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/locked.fyi#5]
The `/<lockAddress>/write` lets the owner of a lock write content as markdown and save it to IPFS.
We need a simple markdown editor to let the user easily type their posts.
Ideally we support a preview so that the author can make sure that their content looks as expected (one of the challenges of publishing on IPFS is that there is no edit possible).

**Comment by kadenzipfel** [comment]
https://github.com/unlock-protocol/locked.fyi/pull/9

**Comment by julien51** [comment]
Thanks @KadenZipfel
