### ISSUE TITLE
DAO Config

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/locked.fyi#55]
The following parameters need to be configured when deploying the lock:
## General
- Organization Name

## Voting
- **Support %**
Support is the relative percentage of tokens that are required to vote “Yes” for a proposal to be approved. For example, if “Support” is set to 50%, then more than 50% of the tokens used to vote on a proposal must vote “Yes” for it to pass.

- **Minimum Approval %**
Minimum Approval is the percentage of the total token supply that is required to vote “Yes” on a proposal before it can be approved. For example, if the “Minimum Approval” is set to 20%, then more than 20% of the outstanding token supply must vote “Yes” on a proposal for it to pass.

- **Vote Duration (Days/Hrs/mins)**

## Tokens
- **Token Name**
- **Token Symbol**
- **Token Holders**
Initialize some addresses balances.

**Comment by nfurfaro** [comment]
For the above fields, This is what I'm thinking:
**Organization Name:** lockedfyi 
**Support:** 50 % ?
**Minimum Approval:** 1% ?
The way I understand the voting params is as follows:
Given 100 shareholders;  
  - at least 1% of them must vote "Yes" for the vote to be valid, 
  - if all of them vote, at least 50 must vote "Yes" for the vote to pass. 
- Note: The Voting app parameters currently cannot be changed from the Aragon frontend client. To change the Voting app parameters after your organization has been created, you must first initialize the permissions to change these parameters, then you can change the parameters using the aragonCLI.



**Vote Duration:** 1 day?
**Token Name:** Locked.fyi shares ?
**Token Symbol:** FYI ?
**Token Holders:** none ?

cc @julien51

**Comment by julien51** [comment]
Organization Name: locked.fyi (if the dot is possible!)
Support: 50 % ✅
Minimum Approval: 1% ✅

Can these 2 things be changed later on? I assume they would be vote themselves?

Vote Duration: I'd do something pretty long, like 10 days. They should be fairly infrequent so I think it's ok?
Token Name: Locked.fyi Shares
Token Symbol: FYI ✅
Token Holders: Can we set an initial supply owned by the Unlock multi-sig like 1000? This is a way to ensure that we have a way to "bootstrap" votes. The idea is that with a 1% participation, we can still avoid the "non-decision" vote until we reach 100k tokens, which would happen when there are a significant number of users!

**Comment by nfurfaro** [comment]
>locked.fyi (if the dot is possible!)

No dots... aragon uses ENS for naming.

>Can these 2 things be changed later on? I assume they would be vote themselves?

No. "The Voting app is instantiated with a certain set of parameters that won’t be changeable for the lifetime of the app:"

>Token Holders: Can we set an initial supply owned by the Unlock multi-sig like 1000?

Pretty sure this is no problem, but will confirm on rinkeby.


https://wiki.aragon.org/archive/dev/apps/voting/

**Comment by julien51** [comment]
Closing as done!
